### ISSUE TITLE
The following error occurred during compilation

### ISSUE THREAD

**Issue by su3817806** [GG2501YT/lineage_hi6250#1]
1 warning generated.
[ 34% 16491/47718] build /home/leji/Li...bj/ETC/sepolicy_intermediates/sepolicy
FAILED: /bin/bash -c "(/home/leji/Lineage/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/policy.conf ) && (/home/leji/Lineage/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/home/leji/Lineage/out/host/linux-x86/bin/sepolicy-analyze /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then        echo \"==========\" 1>&2;         echo \"ERROR: permissive domains not allowed in user builds\" 1>&2;              echo \"List of invalid domains:\" 1>&2; cat /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2;           exit 1;            fi ) && (mv /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy )"
libsepol.report_failure: neverallow on line 63 of system/sepolicy/logd.te (or line 12839 of policy.conf) violated by allow logd cache_file:file { write append };
libsepol.report_failure: neverallow on line 307 of system/sepolicy/init.te (or line 11635 of policy.conf) violated by allow init shell_exec:file { execute_no_trans };
libsepol.report_failure: neverallow on line 353 of system/sepolicy/domain.te (or line 9165 of policy.conf) violated by allow tee default_prop:property_service { set };
libsepol.report_failure: neverallow on line 349 of system/sepolicy/domain.te (or line 9161 of policy.conf) violated by allow perfhub default_android_service:service_manager { add };
libsepol.report_failure: neverallow on line 349 of system/sepolicy/domain.te (or line 9161 of policy.conf) violated by allow hwcamcfgsvr default_android_service:service_manager { add };
libsepol.report_failure: neverallow on line 162 of system/sepolicy/domain.te (or line 8978 of policy.conf) violated by allow tee tee:capability { sys_ptrace };
libsepol.check_assertions: 6 neverallow failures occurred
Error while expanding policy
/home/leji/Lineage/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/policy.conf
[ 34% 16491/47718] target  C++: init <= system/core/init/builtins.cpp
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] 错误 1
make:离开目录“/home/leji/Lineage”

**Comment by GG2501YT** [comment]
You have to apply the patches (cd device/huawei/hi6250/patches && ./patch.sh && croot)

Am 31. Juli 2020 22:19:40 MESZ schrieb "乐鸡" <notifications@github.com>:
>
>
>
>
>1 warning generated.
>
>[ 34% 16491/47718] build /home/leji/Li...bj/ETC/sepolicy_intermediates/sepolicy
>
>FAILED: /bin/bash -c "(/home/leji/Lineage/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/policy.conf ) && (/home/leji/Lineage/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/home/leji/Lineage/out/host/linux-x86/bin/sepolicy-analyze /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then        echo \"==========\" 1>&2;         echo \"ERROR: permissive domains not allowed in user builds\" 1>&2;              echo \"List of invalid domains:\" 1>&2; cat /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2;           exit 1;            fi ) && (mv /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/sepolicy )"
>
>libsepol.report_failure: neverallow on line 63 of system/sepolicy/logd.te (or line 12839 of policy.conf) violated by allow logd cache_file:file { write append };
>
>libsepol.report_failure: neverallow on line 307 of system/sepolicy/init.te (or line 11635 of policy.conf) violated by allow init shell_exec:file { execute_no_trans };
>
>libsepol.report_failure: neverallow on line 353 of system/sepolicy/domain.te (or line 9165 of policy.conf) violated by allow tee default_prop:property_service { set };
>
>libsepol.report_failure: neverallow on line 349 of system/sepolicy/domain.te (or line 9161 of policy.conf) violated by allow perfhub default_android_service:service_manager { add };
>
>libsepol.report_failure: neverallow on line 349 of system/sepolicy/domain.te (or line 9161 of policy.conf) violated by allow hwcamcfgsvr default_android_service:service_manager { add };
>
>libsepol.report_failure: neverallow on line 162 of system/sepolicy/domain.te (or line 8978 of policy.conf) violated by allow tee tee:capability { sys_ptrace };
>
>libsepol.check_assertions: 6 neverallow failures occurred
>
>Error while expanding policy
>
>/home/leji/Lineage/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /home/leji/Lineage/out/target/product/hi6250/obj/ETC/sepolicy_intermediates/policy.conf
>
>[ 34% 16491/47718] target  C++: init <= system/core/init/builtins.cpp
>
>ninja: build stopped: subcommand failed.
>
>make: *** [ninja_wrapper] 错误 1
>
>make:离开目录“/home/leji/Lineage”
>
>
>
>#### make failed to build some targets (29:45 (mm:ss)) ####
>
>
>
>
>
>
>
>-- >
>You are receiving this because you are subscribed to this thread.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/GG2501YT/lineage_hi6250/issues/1
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by su3817806** [comment]
@GG2501YT Success ~ thank you
